---
title: "Slides"
page-layout: full
---

## Tentative Course Schedule

Below is a tentative schedule of topics for the term. You can find the lecture slides in html format, my annotated slides as a pdf, as well as the pdf versions of the tutorial slides. When annotating the html slides in class, you can save them by printing to pdf in your browser. However, I have also included the slides in PDF format as I was made aware that the formatting can be a little strange when printing them yourself.

::: {.table-responsive}
| Week | Topics | Lecture Slides | Tutorial | Assessments | Suggested Reading \[ISL\] |
|:----------:|:-----------|:----------:|:-----------|:-----------|:-----------|
| 1 | Introduction to Statistical Learning; Supervised Learning; Model Assessment | [HTML Slides](Week1.html)<br>[PDF Slides](Week1 - PDF.pdf)<br>[Recorded Lecture](https://youtu.be/OpLpm7I4btY)| \- | — | Ch. 2 |
| 2 | Linear Regression; Model Assessment and Selection | [HTML Slides](Week2-slides.html)<br>[PDF Slides](Week2 - PDF.pdf)<br>[Annotated Slides](Week2-Annotated.pdf) | \- | \- | Ch. 3, 5 |
| 3 | Shrinkage/Regularization | [HTML Slides](Week3.html)<br>[PDF Slides](Week3-PDF.pdf) | [Slides](Tutorial1-Slides.pdf)<br>[R Code](Tutorial1.Rmd)<br>[RMarkdown PDF](Tutorial1.pdf) | [Assignment 1 Released](STA314_Assignment_1.pdf), Sept. 23rd | Ch. 6 | 
| 4 | Moving Beyond Linearity | \- | \- | \-  | Ch. 7 |
| 5 | Classification: Bayes Classifier, kNN and Logistic Regression | \- | \- | Assignment 1 Due, Oct. 7 | Ch. 4 |
| 6 | Classification: Multiclass Logistic Regression and Discriminant Analysis | \- | \- | \- | Ch. 4 |
| 7 | Tree Based Methods: Decision Trees | \- | \- | \- | Ch. 8 |
| 8 | **Reading Week** | \- | \- | \- | \- |
| 9 | Tree Based Methods: Bagging, Random Forests, and Boosting | \- | \- | Midterm, Nov. 4 | Ch. 8 |
| 10 | Support Vector Machines | \- | \- | \- | Ch. 9 |
| 11 | Unsupervised Learning: PCA and Clustering | \- | \- | Assignment 2 Released, Nov. 18 | Ch. 12 |
| 12 | Gradient Descent; Neural Networks | \- | \- | \- | Ch. 10 |
| 13 | Neural Networks;Generative AI; Course Review | \- | \- | Assignment 2 Due, Dec 2nd | Ch. 10 |
:::
