---
title: "STA314"
---

## Welcome to Statistical Methods for Machine Learning I!

This course will introduce you to the statistical ideas that underpin many modern machine learning methods. Some of the concepts may be challenging, and I expect you to think critically, ask questions, and actively engage with the material. My goal is not only to help you learn the techniques, but also to develop an understanding of why they work and when they should be used. I have high expectations because I believe every student in this course is capable of developing a strong understanding of the material through effort, curiosity, and persistence.

I am committed to creating a welcoming, respectful, and inclusive learning environment where everyone feels comfortable participating. Please don't hesitate to ask questions during lectures, tutorials, office hours, or on Piazza. If you're struggling, reach out early. I am here to support you throughout your learning journey.

I hope this course leaves you with not only a strong foundation in statistical methods for machine learning, but also the confidence to think critically about data and the models you build. I'm looking forward to a great semester with all of you!

## Announcements

-   The [Syllabus](STA314-Syllabus.pdf) is available.

-   Announcements will be through [Quercus](https://q.utoronto.ca/courses/462956) and here, on the course website.

## Course Information

All information can be found in the [Syllabus](STA314-Syllabus.pdf).

Just a few important points: 

- all date information, location information, and most of the course material will be posted on this course website

- non-public material will be posted on [Quercus](https://q.utoronto.ca/courses/462956)

- to email me, email sta314\@course.utoronto.ca

- I will not respond to emails sent to my individual account 

- all lectures, tutorials, and tests will be delivered in person, unless otherwise specified 

- there will be one midterm test scheduled during the scheduled class time, and we will have a FAS proctored final examination 

- the textbook we will be using this term is the [Introduction to Statistical Learning](https://www.statlearning.com/) by James et al.

## Computing

Statistical programming is an essential part of this course. We will use R throughout this course, which is a free, open-source statistical programming language widely used for data analysis and reproducible research.

The software is publicly available for free [here](https://mirror.csclub.uwaterloo.ca/CRAN/), and it is also highly recommended to install [RStudio](https://posit.co/downloads/) for an interactive programming environment. Note that the University of Toronto offers an [open-source web application](https://r.datatools.utoronto.ca/) to use R and RStudio.
