<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <title>STA314 – Bayes Classifier, k-Nearest Neighbours, and Logistic Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-2f366650f320edcfcf53d73c80250a32.css">
  <link rel="stylesheet" href="styles.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script type="module" src="site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
  <link href="site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Bayes Classifier, k-Nearest Neighbours, and Logistic Regression</h1>
  <p class="subtitle">Week 5</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="review-case-study" class="slide level2 scrollable">
<h2>Review: Case Study</h2>
<p>A hospital wants to build a model to predict a patient’s <strong>recovery time after surgery</strong>, measured in days. They have data from <strong>2,000 previous patients</strong> and 22 predictors, including:</p>
<ul>
<li>age; BMI; length of surgery; blood loss during surgery; several pre-operative blood test measurements; physical activity level; sleep duration; 15 additional clinical measurements</li>
</ul>
<div class="fragment">
<p>Exploratory analysis suggests that:</p>
<ul>
<li>recovery time tends to increase with <strong>age</strong>, but the relationship does not appear linear;</li>
<li>the effect of <strong>BMI</strong> may also be nonlinear;</li>
<li>several of the blood-test measurements are <strong>strongly correlated</strong>;</li>
<li>some of the clinical measurements may have little or no relationship with recovery time.</li>
</ul>
</div>
<div class="fragment">
<p>Come up with a <strong>modelling plan</strong></p>
<ol type="1">
<li>What model or models would you consider and why?</li>
<li>How would you compare models, and how would you estimate how well your final model will perform on new patients?</li>
</ol>
</div>
</section>
<section id="learning-outcomes" class="slide level2 scrollable">
<h2>Learning Outcomes</h2>
<p>By the end of this lecture, you should be able to:</p>
<ol type="1">
<li><p>Explain the Bayes classifier and why the Bayes error rate represents the smallest achievable expected classification error.</p></li>
<li><p>Describe how kNN performs classification, explain how <span class="math inline">\(k\)</span> affects model flexibility, and use cross-validation to select <span class="math inline">\(k\)</span>.</p></li>
<li><p>Interpret logistic regressioncoefficients and predicted probabilities, and explain how maximum likelihood and gradient descent estimate the model parameters.</p></li>
<li><p>Evaluate binary classifiers using a confusion matrix and appropriate performance metrics, and explain how changing the classification threshold affects false positives and false negatives.</p></li>
</ol>
</section>
<section>
<section id="bayes-classifier" class="title-slide slide level1 center">
<h1>Bayes Classifier</h1>

</section>
<section id="introduction-to-classification-problems" class="slide level2">
<h2>Introduction to Classification Problems</h2>
<p>The response variable <span class="math inline">\(Y\)</span> is <span style="color: maroon;">qualitative</span>: it takes values in a set of class labels <span class="math inline">\(\mathcal{C}\)</span>.</p>
<ul>
<li><p><span style="color: maroon;">Binary classification:</span> <span class="math inline">\(|\mathcal{C}|=2\)</span></p>
<ul>
<li>Email: <span class="math inline">\(\{\text{spam},\text{not spam}\}\)</span></li>
<li>Patient status: <span class="math inline">\(\{\text{cancer},\text{no cancer}\}\)</span></li>
</ul>
<p><br></p></li>
<li><p><span style="color: maroon;">Multiclass classification:</span> <span class="math inline">\(|\mathcal{C}|&gt;2\)</span></p>
<ul>
<li>Handwritten digit: <span class="math inline">\(\{0,1,\ldots,9\}\)</span></li>
<li>Eye colour: <span class="math inline">\(\{\text{brown},\text{blue},\text{green}\}\)</span></li>
</ul></li>
</ul>
</section>
<section id="classification" class="slide level2">
<h2>Classification</h2>
<p>Given training data <span class="math inline">\(\mathcal{D}_{\mathrm{train}}=\{(x_1,y_1),\ldots,(x_n,y_n)\}\)</span>, with <span class="math inline">\(x_i\in\mathbb{R}^p\)</span> and <span class="math inline">\(y_i\in\mathcal{C}\)</span>, we want to:</p>
<ul>
<li>Build a <span style="color: maroon;">classifier</span> <span class="math inline">\(\hat f:\mathbb{R}^p\to\mathcal{C}\)</span> that assigns a class label <span class="math inline">\(\hat f(x)\)</span> to a new observation <span class="math inline">\(x\)</span>.</li>
<li>Assess its <span style="color: maroon;">classification accuracy</span>.</li>
<li>Understand how the predictors affect its classifications.</li>
</ul>
</section>
<section id="regression-or-classification" class="slide level2 scrollable">
<h2>Regression or Classification?</h2>
<p>Determine whether each scenario is a classification or regressi0on problem.</p>
<ol type="1">
<li>We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.</li>
</ol>
<textarea class="annotation-box" placeholder="Type notes here..."></textarea>
<ol start="2" type="1">
<li>We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.</li>
</ol>
<textarea class="annotation-box" placeholder="Type notes here..."></textarea>
<ol start="3" type="1">
<li>We are interested in predicting the % change in the USD/Euro exchange rate in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. For each week we record the % change in the USD/Euro, the % change in the US market, the % change in the British market, and the % change in the German market.</li>
</ol>
<textarea class="annotation-box" placeholder="Type notes here..."></textarea>
</section>
<section id="measuring-classification-error" class="slide level2">
<h2>Measuring Classification Error</h2>
<p>Let <span class="math inline">\((X,Y)\)</span> be a new observation independent of the training data. Let us encode the labels as</p>
<p><span class="math display">\[
C = \{0,1,2,...,K-1\}.
\]</span></p>
<p>For any classifier <span class="math inline">\(\hat f\)</span>, we evaluate it based on the <span style="color: maroon;">expected error rate</span></p>
<p><span class="math display">\[
\mathbb{E}\!\left[\mathbf{1}\{Y\ne\hat f(X)\}\right].
\]</span></p>
<p><br></p>
<p><strong>Question</strong>: Which classifier has the smallest expected error?</p>
</section>
<section id="an-analogy-with-regression" class="slide level2">
<h2>An Analogy with Regression</h2>
<p>In regression, under <span class="math inline">\(Y=f^*(X)+\varepsilon\)</span>, the regression function is the best predictor: for any <span class="math inline">\(x \in \mathbb{R}^p\)</span>,</p>
<p><span class="math display">\[
f^*(x)=\mathbb{E}(Y\mid X=x)
=\underset{\widehat{f}(x)}{\arg\min}\;\mathbb{E}\!\left[(Y-\widehat{f}(X))^2\mid X=x\right].
\]</span></p>
<p>Its MSE is the smallest (i.e.&nbsp;the irreducible error),</p>
<p><span class="math display">\[
\mathbb{E}[(Y - f^*(X))^2] = Var(\epsilon) = \sigma^2
\]</span></p>
</section>
<section id="the-bayes-classifier" class="slide level2">
<h2>The Bayes Classifier</h2>
<p>The <span style="color: maroon;">Bayes classifier</span> (sometimes called Bayes rule) is a function: <span class="math inline">\(f^*: \mathbb{R}^p \rightarrow C\)</span> that minimizes the expected error rate as</p>
<p><span class="math display">\[
f^*(x)=\underset{\widehat{f}(x)\in C}{\arg\min}\;\mathbb{E}[1\{Y \neq \widehat{f}(X)\}|X=x] \quad \forall x \in \mathbb{R}^p.
\]</span> Correspondingly, its expected error rate</p>
<p><span class="math display">\[
\mathbb{E}[1\{Y \neq f^*(X)\}]
\]</span></p>
<p>is called the <span style="color: maroon;">Bayes error rate</span> which is the smallest.</p>
</section>
<section id="deriving-the-bayes-classifier" class="slide level2">
<h2>Deriving the Bayes Classifier</h2>
<p>For any <span class="math inline">\(x \in \mathbb{R}^p\)</span>,</p>
<p><span class="math display">\[
\begin{aligned}
f^*(x)
&amp;= \underset{\widehat{f}(x)\in C}{\arg\min}\;\mathbb{E}[1\{Y \neq \widehat{f}(X)\}|X=x] \\
&amp;= \underset{\widehat{f}(x)\in C}{\arg\min}\; \mathbb{P}\{Y \neq \widehat{f}(X)|X=x\} \\
&amp;= \underset{\widehat{f}(x)\in C}{\arg\max}\; \mathbb{P}\{Y = \widehat{f}(X)|X=x\}
\end{aligned}
\]</span></p>
<p>It is easy to see that</p>
<p><span class="math display">\[
\underset{k\in C}{\arg\max}\; \mathbb{P}\{Y = k|X=x\}
\]</span> The Bayes classifier, <span class="math inline">\(f^*\)</span>, is our target to estimate/learn in classification problems.</p>
</section>
<section id="bayes-error-rate" class="slide level2">
<h2>Bayes Error Rate</h2>
<p>The Bayes error rate at <span class="math inline">\(X=x\)</span> is</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}[\mathbf{1}\{Y\ne f^*(x)\}\mid X=x]
&amp;=\mathbb{P}(Y\ne f^*(x)\mid X=x)\\
&amp;=1-\mathbb{P}(Y=f^*(x)\mid X=x) \\
&amp;=1-\underset{j\in C}{\max}\; \mathbb{P}\{Y = j \mid X=x\}
\end{aligned}
\]</span></p>
<div class="fragment">
<p>The Bayes error rate is:</p>
<ul>
<li>between 0 and 1</li>
<li>typically <span class="math inline">\(\neq\)</span> 0</li>
</ul>
</div>
<div class="fragment">
<p>In general, the overall Bayes error rate is given by</p>
<p><span class="math display">\[
1 - \mathbb{E}\left(\underset{j\in C}{\max}\; \mathbb{P}(y=j \mid X=x) \right)
\]</span> where the expectation averages the probability over all possible values of <span class="math inline">\(X\)</span>.</p>
</div>
</section>
<section id="binary-classification" class="slide level2">
<h2>Binary Classification</h2>
<p>For <span class="math inline">\(\mathcal{C}=\{0,1\}\)</span>, define the <span style="color: maroon;">conditional probability</span>:</p>
<p><span class="math display">\[p(x)=\mathbb{P}(Y=1\mid X=x),\qquad p:\mathbb{R}^p\to\{0,1\}.\]</span></p>
<p>The Bayes rule is</p>
<p><span class="math display">\[
f^*(x)=
\begin{cases}
1,&amp;p(x)\geq 0.5,\\
0,&amp;p(x)&lt;0.5.
\end{cases}
\]</span></p>
<p>The choice at exactly <span class="math inline">\(0.5\)</span> is arbitrary: both labels have the same conditional error.</p>
</section>
<section id="example-the-binary-case" class="slide level2">
<h2>Example: The Binary Case</h2>

<img data-src="images/Week5-BayesBoundary.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"><p>A simulated data set consisting of 100 observations in each of two groups, indicated in blue and in orange. The purple dashed line represents the <strong>Bayes decision boundary</strong>. The orange background grid indicates the region in which a test observation will be assigned to the orange class, and the blue background grid indicates the region in which a test observation will be assigned to the blue class.</p>
</section>
<section id="k-nearest-neighbours-for-classification" class="slide level2">
<h2>K-Nearest Neighbours for Classification</h2>
<p>For real data, we do not know the conditional distribution of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>, so computing the Bayes classifier is impossible.</p>
<p><br></p>
<p>However, we can use the <em>k-Nearest Neighbours</em> approach, which estimates the conditional distribution of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>, and then classifies a given observation to the class with the highest <em>estimated</em> probability.</p>
</section>
<section id="a-classical-local-approach-nearest-neighbours" class="slide level2">
<h2>A Classical Local Approach: Nearest Neighbours</h2>
<ul>
<li>Consider a <strong>classification problem</strong></li>
<li>Suppose we are given a new feature vector, <span class="math inline">\(\mathbf{x^*} \in \mathbb{R}^p\)</span></li>
<li>The idea here is the find the nearest feature vector to <span class="math inline">\(\mathbf{x}\)</span> in the training set, and use its label to predict <span class="math inline">\(y^*\)</span></li>
</ul>
<div class="fragment">
<p>There are many ways that we can <em>define nearest</em>, but for now we will use the <span style="color: maroon;">Euclidean distance</span>, i.e.</p>
<p><span class="math display">\[||\mathbf{x_i}-\mathbf{x_{i'}}||_2 = \sqrt{\sum_{j=1}^p (x_{ij} - x_{i'j})^2}\]</span></p>
</div>
</section>
<section id="a-classical-local-approach-nearest-neighbours-1" class="slide level2 scrollable">
<h2>A Classical Local Approach: Nearest Neighbours</h2>
<div class="algorithm-box">
<p><strong>Algorithm: 1-NN</strong></p>
<ol type="1">
<li><p>Find example <span class="math inline">\((\mathbf{x}, y)\)</span> (from the training data) closest to <span class="math inline">\(\mathbf{x^*}\)</span>. That is: <span class="math display">\[\mathbf{x} = \underset{\mathbf{x_i} \in \{\mathbf{x_1}, ..., \mathbf{x_n}\}}{\arg\min} \text{distance}(\mathbf{x_i}, \mathbf{x^*})\]</span></p></li>
<li><p>Output <span class="math inline">\(y\)</span> as the label.</p></li>
</ol>
</div>
</section>
<section id="a-classical-local-approach-nearest-neighbours-2" class="slide level2">
<h2>A Classical Local Approach: Nearest Neighbours</h2>
<p>We can visualize the behaviour in the classification setting using a <span style="color: maroon;">Voronoi diagram</span>.</p>
<p>This diagram is a way to divide a space into different regions based on the distance to specific points, thus it’s a good way to visualize what the outcome label of a new point, <span class="math inline">\(\mathbf{x^*}\)</span> would be.</p>

<img data-src="images/Week2-Voronoi.png" class="quarto-figure quarto-figure-center r-stretch" style="width:40.0%"></section>
<section id="nearest-neighbours-decision-boundaries" class="slide level2">
<h2>Nearest Neighbours: Decision Boundaries</h2>
<p><span style="color: maroon;">Decision Boundary</span>: the boundary between regions of the feature space assigned to different categories</p>

<img data-src="images/Week2-DecisionBoundary.png" class="quarto-figure quarto-figure-center r-stretch" style="width:45.0%"></section>
<section id="lets-generalize-k-nearest-neighbours" class="slide level2 scrollable">
<h2>Let’s Generalize: k-Nearest Neighbours</h2>
<p>Instead of just using the <em>nearest</em> neighbour, we will use the <em>k-nearest neighbours</em>.</p>
<div class="algorithm-box">
<p><strong>Algorithm: k-NN for Classification</strong></p>
<ol type="1">
<li><p>Find <span class="math inline">\(k\)</span> data points <span class="math inline">\((\mathbf{x_{(1)}}, y_{(1)}), ..., (\mathbf{x_{(k)}}, y_{(k)})\)</span> (from the training data) closest to <span class="math inline">\(\mathbf{x^*}\)</span>. These points are ordered by which are closest to <span class="math inline">\(\mathbf{x^*}\)</span>. These points form a neighbourhood, <span class="math inline">\(N_k(\mathbf{x})\)</span>.</p></li>
<li><p>The prediction for a classification problem is majority class among the <span class="math inline">\(k\)</span> neighbours</p></li>
</ol>
<p><span class="math display">\[
   \hat{y}^*
   =
   \underset{y \in \mathcal{C}}{\arg\max}
   \sum_{i=1}^{k}
   \mathbf{1}\{y = y_{(i)}\},
\]</span></p>
<p>where <span class="math inline">\(\mathcal{C}\)</span> is the set of possible classes.</p>
</div>
</section>
<section id="knn" class="slide level2">
<h2>kNN</h2>
<p>Below, the <span class="math inline">\(k\)</span>NN approach, using <span class="math inline">\(k=3\)</span>, is shown in a simple situation of six blue and six orange observations.</p>

<img data-src="images/Week5-kNN.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"><p><strong>Left</strong>: Test observation is the black cross. The three closest points are shown within the green circle. The prediction will be that the test observation belongs to the blue class, since that is the most commonly-occuring class.</p>
<p><strong>Right</strong>: <span class="math inline">\(k\)</span>NN decision boundary is shown in black.</p>
</section>
<section id="knn-1" class="slide level2">
<h2>kNN</h2>

<img data-src="images/Week5-kNN10.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"><p>The black curve indicates the <span class="math inline">\(k\)</span>NN decision boundary on simulated data using K = 10. The Bayes decision boundary is shown as a purple dashed line.</p>
</section>
<section id="tradeoffs-in-choosing-k" class="slide level2">
<h2>Tradeoffs in Choosing <span class="math inline">\(k\)</span></h2>
<p><strong>Small</strong> <span class="math inline">\(k\)</span></p>
<ul>
<li>More flexible decision boundary, but high variance
<ul>
<li><span style="color: maroon;">Question</span>: what does high variance mean when we’re talking about <span class="math inline">\(\hat{f}\)</span>?</li>
</ul></li>
<li>Overfitting: sensitive to random noise in the training data</li>
</ul>
<p><strong>Large</strong> <span class="math inline">\(k\)</span></p>
<ul>
<li>Less flexible decision boundary and smaller variance</li>
<li>Underfitting: fail to capture the true decision boundary</li>
</ul>
</section>
<section id="example-tradeoffs-in-choosing-k" class="slide level2">
<h2>Example: Tradeoffs in Choosing <span class="math inline">\(k\)</span></h2>

<img data-src="images/Week5-kNNComparison.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"></section>
<section id="tradeoffs-in-choosing-k-1" class="slide level2">
<h2>Tradeoffs in Choosing <span class="math inline">\(k\)</span></h2>
<p><strong>Balancing</strong> <span class="math inline">\(k\)</span></p>
<ul>
<li>Optimal choice of <span class="math inline">\(k\)</span> depends on number of data points, <span class="math inline">\(n\)</span></li>
</ul>
<p><br></p>
<p><span style="color: maroon;">Rule of Thumb</span>: Choose <span class="math inline">\(k\)</span> from <span class="math inline">\([1, \sqrt{n}]\)</span> via cross-validation.</p>
</section>
<section id="pitfalls-the-curse-of-dimensionality" class="slide level2">
<h2>Pitfalls: The Curse of Dimensionality</h2>
<p>As we have discussed many times, <span style="color: maroon;">kNN suffers from the curse of dimensionality!</span></p>
<ul>
<li>In high dimensions, “most” points are approximately the same distance because they are far away from each other</li>
</ul>
<div class="fragment">
<p>The saving grade is that some datasets (e.g.&nbsp;images) may have low <span style="color: maroon;">intrinsic dimension</span></p>
<ul>
<li>This means that high dimensional data may rely on a much smaller number of true independent variables than the space may suggest</li>
<li>i.e.&nbsp;The true <span class="math inline">\(f\)</span> does not use all features available</li>
</ul>
</div>
</section>
<section id="pitfalls-normalization" class="slide level2">
<h2>Pitfalls: Normalization</h2>
<p><span class="math inline">\(k\)</span>NN can be sensitive to the ranges of different features</p>
<ul>
<li>e.g.&nbsp;Motivating example: age (50+) vs.&nbsp;indicator variable representing whether the patient can bathe on their own (0 or 1)</li>
</ul>
<p><br></p>
<div class="fragment">
<p>A simple fix: <span style="color: maroon;">standardize</span> each dimension to be zero mean and unit variance.</p>
<p><strong>Caution</strong>: depending on the problem, the scale might be important!</p>
</div>
</section>
<section id="pitfalls-computational-cost" class="slide level2">
<h2>Pitfalls: Computational Cost</h2>
<ul>
<li><p>Computational cost for classifying test data, per data point (un-modified algorithm)</p>
<ul>
<li>Calculate p-dimensional Euclidean distances with <span class="math inline">\(n\)</span> data points: O(<span class="math inline">\(np\)</span>) (computation time increases linearly with n and with p)</li>
<li>Sort the distances: O(<span class="math inline">\(n \log n\)</span>) (computation time between linear and quadratic)</li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li>This must be done for each test data point, which is very expensive by the standards of a learning algorithm!</li>
<li>Need to store the entire dataset in memory!</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Tons of work has gone into algorithms and data structures for efficient nearest neighbors with high dimensions and/or large datasets.</li>
</ul>
</div>
</section>
<section id="note-on-other-distance-measures" class="slide level2">
<h2>Note on Other Distance Measures</h2>
<p>Depending on the type of dataset, <span style="color: maroon;">different distance measures will perform better than others</span>.</p>
<p><br> These distance measures may differ in:</p>
<ul>
<li>their sensitivity to large differences in feature values</li>
<li>their ability to handle non-continuous features</li>
<li>their ability to perform well in sparse feature environments</li>
<li>etc.</li>
</ul>
</section>
<section id="knowledge-check" class="slide level2 scrollable">
<h2>Knowledge Check</h2>
<p>Which of the following statements are true:</p>
<ol type="1">
<li>kNN is a parametric method.</li>
<li>Increasing <span class="math inline">\(k\)</span> reduces the variance of the <span class="math inline">\(k\)</span>NN prediction.</li>
<li>Cross-validation cannot be used to select the value of <span class="math inline">\(k\)</span>.</li>
<li><span class="math inline">\(k\)</span>NN assigns more weights for prediction to closer neighbours.</li>
</ol>
</section>
<section id="knowledge-check-1" class="slide level2 scrollable">
<h2>Knowledge Check</h2>
<p>Which of the following statements are true:</p>
<ol type="1">
<li>The Bayes classifier usually has the smallest training error rate among all possible classifiers .</li>
<li>The Bayes classifier usually has the smallest expected test error rate among all possible classifiers.<br>
</li>
<li>When <span class="math inline">\(Y\)</span> has three categories (e.g, <span class="math inline">\(Y \in \{1,2,3\}\)</span>), the Bayes error rate can be greater than 0.5.</li>
<li>The training error rate of the Bayes classifier is always greater than 0.</li>
</ol>
</section>
<section id="why-not-use-linear-regression" class="slide level2">
<h2>Why Not Use Linear Regression?</h2>
<p>Consider the following problem. We are trying to predict the medical condition of a patient in the emergency room on the basis of her symptoms.</p>
<p>There are three possible diagnoses: stroke, drug overdose, and epileptic seizure.</p>
<p>We define <span class="math inline">\(Y\)</span> as follows:</p>
<p><span class="math display">\[
Y = \begin{cases}
  1 \quad \text{if stroke}; \\
  2 \quad \text{if drug overdose}; \\
  3 \quad \text{if epileptic seizure}.
\end{cases}
\]</span> Could we use OLS to fit a linear regressions model to predict <span class="math inline">\(Y\)</span> on the basis of a set of predictors <span class="math inline">\(X_1, X_2, ..., X_p\)</span>?</p>
<textarea class="annotation-box" placeholder="Type notes here..."></textarea>
</section>
<section id="why-not-use-linear-regression-1" class="slide level2">
<h2>Why Not Use Linear Regression?</h2>
<p>For a binary qualtitative response, the situation is better. Consider that there are only two possibilities for the patient’s medical condition:</p>
<p><span class="math display">\[
Y = \begin{cases}
  0 \quad \text{if stroke}; \\
  1 \quad \text{if drug overdose}.
\end{cases}
\]</span> We could fit a linear regression to this binary response, and predict drug overdose if <span class="math inline">\(\hat{p}(x) = \hat{Y} &gt; 0.5\)</span> and stroke otherwise</p>
<div class="fragment">
<p>OLS gives fitted values of the form</p>
<p><span class="math display">\[\hat p(x)=\hat\beta_0+\hat\beta_1x_1+\cdots+\hat\beta_px_p.\]</span></p>
<p>This expression can be less than 0 or greater than 1, even though probabilities must lie in <span class="math inline">\([0,1]\)</span>.</p>
<p>A more tailored approach is needed.</p>
</div>
</section>
<section id="linear-versus-logistic-regression" class="slide level2">
<h2>Linear Versus Logistic Regression</h2>

<img data-src="images/Week5-LogisticRegression.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"><p>Linear regression can predict probabilities below zero; logistic regression produces predictions in <span class="math inline">\([0,1]\)</span>. The plotted points show the observed 0/1 default outcomes.</p>
</section>
<section id="classification-approaches" class="slide level2">
<h2>Classification Approaches</h2>
<p>How can we estimate <span class="math display">\[
p(x) = \mathbb{P}\{Y=1|X=x\}
\]</span></p>
<p>or, more generally,</p>
<p><span class="math display">\[
\mathbb{P}\{Y=k\mid X=x\} \quad \forall k \in C
\]</span> for any <span class="math inline">\(x \in \mathbb{R}^p\)</span>?</p>
<p><br></p>
<div class="fragment">
<ul>
<li><span style="color: maroon;">Parametric methods:</span> logistic regression; discriminant analysis.</li>
<li><span style="color: maroon;">Nonparametric methods:</span> <span class="math inline">\(k\)</span>-nearest neighbours; classification trees; support vector machines.</li>
</ul>
<p>These methods make different assumptions about the relationship between predictors and class labels.</p>
</div>
</section>
<section id="how-to-select-among-a-set-of-classifiers" class="slide level2">
<h2>How to Select Among a Set of Classifiers</h2>
<p>For a given classifier <span class="math inline">\(\hat{f}: \mathbb{R}^p \rightarrow C\)</span>, we have</p>
<p><br></p>
<p><span style="color: maroon;"><strong>Training 0-1 Error Rate</strong></span></p>
<p><span class="math display">\[
\frac{1}{n}\sum_{i=1}^n 1\{y_i \neq \hat{f}(x_i)\}
\]</span></p>
<p><span style="color: maroon;"><strong>Test 0-1 Error Rate</strong></span> when we have the test data <span class="math inline">\(\{(x_{T_1}, y_{T_1}), ..., (x_{T_m}, y_{T_m})\}\)</span>,</p>
<p><span class="math display">\[
\frac{1}{m}\sum_{i=1}^m 1\{y_i \neq \hat{f}(x_{T_i})\}
\]</span></p>
</section>
<section id="how-to-select-among-a-set-of-classifiers-1" class="slide level2">
<h2>How to Select Among a Set of Classifiers</h2>
<ul>
<li><p><span style="color: maroon;">Data splitting based on 0-1 error rate</span> when we don’t have the test data</p>
<ul>
<li>Validation-set approach</li>
<li>Cross-validation</li>
</ul></li>
</ul>
<p><br></p>
<ul>
<li>More metrics on binary classification</li>
</ul>
</section></section>
<section>
<section id="logistic-regression" class="title-slide slide level1 center">
<h1>Logistic Regression</h1>

</section>
<section id="logistic-regression-1" class="slide level2">
<h2>Logistic Regression</h2>
<p><span style="color: maroon;">Logistic regression</span> is a parametric approach that postulates parametric structure on the function <span class="math inline">\(p: \mathcal{X} \rightarrow [0,1]\)</span>.</p>
<p>It is assumed that</p>
<p><span class="math display">\[
p(\boldsymbol{x}) :=p(\boldsymbol{x};\boldsymbol\beta)=
\frac{e^{\beta_0+\beta_1x_1+\cdots+\beta_px_p}}
{1+e^{\beta_0+\beta_1x_1+\cdots+\beta_px_p}} \quad \forall \boldsymbol{x} \in \mathcal{X}
\]</span></p>
<div class="fragment">
<ul>
<li><p>The function <span class="math inline">\(f(t)=e^t/(1+e^t)\)</span> is the <span style="color: maroon;">logistic function</span>.</p></li>
<li><p><span class="math inline">\(\beta_0,\ldots,\beta_p\)</span> are the model parameters.</p></li>
<li><p>For finite coefficients and predictor values, <span class="math inline">\(0&lt;p(\boldsymbol{x})&lt;1\)</span>.</p></li>
<li><p><span class="math inline">\(p(\boldsymbol{x};\boldsymbol\beta)\)</span> is <span style="color: maroon;">nonlinear</span> in both <span class="math inline">\(\boldsymbol{x}\)</span> and <span class="math inline">\(\boldsymbol\beta\)</span>.</p></li>
</ul>
</div>
</section>
<section id="logistic-regression-2" class="slide level2">
<h2>Logistic Regression</h2>
<p>Rearranging the logistic model gives</p>
<p><span class="math display">\[
\underbrace{\frac{p(x)}{1-p(x)}}_{\text{odds}}
=e^{\beta_0+\beta_1x_1+\cdots+\beta_px_p}.
\]</span></p>
<p><span class="math display">\[
\underbrace{\log\left(\frac{p(x)}{1-p(x)}\right)}_{\text{log-odds (logit)}}
=\beta_0+\beta_1x_1+\cdots+\beta_px_p.
\]</span></p>
<ul>
<li>Odds lie in <span class="math inline">\((0,\infty)\)</span> and log-odds lie in <span class="math inline">\((-\infty,\infty)\)</span>.</li>
<li>Holding other predictors fixed, a one-unit increase in <span class="math inline">\(X_j\)</span> changes the <span style="color: maroon;">log-odds</span> by <span class="math inline">\(\beta_j\)</span> and multiplies the odds by <span class="math inline">\(e^{\beta_j}\)</span>.</li>
</ul>
</section>
<section id="logistic-regression-3" class="slide level2">
<h2>Logistic Regression</h2>
<p>Our interests:</p>
<ul>
<li><span style="color: maroon;">Prediction</span>: for a new predictor vector <span class="math inline">\(\boldsymbol{x}_0 \in \mathcal{X}\)</span>, estimate the probability of class 1 and classify its corresponding label <span class="math inline">\(y_0\)</span>.</li>
</ul>
<p><br></p>
<ul>
<li><span style="color: maroon;">Estimation</span>: estimate <span class="math inline">\(\boldsymbol\beta\)</span> using the training data.</li>
</ul>
</section>
<section id="predictions-under-logistic-regression" class="slide level2 scrollable">
<h2>Predictions Under Logistic Regression</h2>
<p>Given estimates <span class="math inline">\(\widehat{\boldsymbol\beta}=(\widehat\beta_0,\ldots,\widehat\beta_p)\)</span>:</p>
<ol type="1">
<li>Predict the <span style="color: maroon;">logit</span> at <span class="math inline">\(\boldsymbol{x} \in \mathcal{X}\)</span>:</li>
</ol>
<p><span class="math display">\[
\widehat{\text{logit}}(\boldsymbol{x})=\widehat\beta_0+\widehat\beta_1x_1+\cdots+\widehat\beta_px_p.
\]</span></p>
<ol start="2" type="1">
<li>Predict the <span style="color: maroon;">conditional probability</span> <span class="math inline">\(p(\boldsymbol{x}) = \mathbb{P}(Y=1 \mid X=\boldsymbol{x})\)</span>:</li>
</ol>
<p><span class="math display">\[
\widehat p(x)=\frac{e^{\widehat\beta_0+\widehat\beta_1x_1+\cdots+\widehat\beta_px_p}}{1+e^{\widehat\beta_0+\widehat\beta_1x_1+\cdots+\widehat\beta_px_p.}}.
\]</span></p>
<ol start="3" type="1">
<li>Classify the <span style="color: maroon;">label</span> <span class="math inline">\(Y\)</span> at <span class="math inline">\(X = \boldsymbol{x}\)</span>:</li>
</ol>
<p><span class="math display">\[
\widehat y=\begin{cases}1,&amp;\widehat p(x)\geq 0.5,\\0,&amp;\widehat p(x)&lt;0.5.\end{cases}
\]</span></p>
</section>
<section id="maximum-likelihood-estimator-mle" class="slide level2">
<h2>Maximum Likelihood Estimator (MLE)</h2>
<p>Given training data <span class="math inline">\(\mathcal D^{\text{train}}=\{(x_i,y_i):i=1,\ldots,n\}\)</span> with <span class="math inline">\(y_i\in\{0,1\}\)</span>, we estimate the parameters by <span style="color: maroon;">maximizing the likelihood</span> of <span class="math inline">\(\mathcal D^{\mathrm{train}}\)</span>.</p>
<p><br></p>
<div class="fragment">
<p><strong>The maximum likelihood principle</strong>: We seek the estimates of parameters such that the fitted probability are the closest to the individual’s observed outcome.</p>
</div>
</section>
<section id="computing-the-mle" class="slide level2 scrollable">
<h2>Computing the MLE</h2>
<p>The general steps are:</p>
<p><br></p>
<ol type="1">
<li>Write down the <span style="color: maroon;">likelihood</span>.</li>
<li>Solve the <span style="color: maroon;">optimization problem</span>.</li>
</ol>
</section>
<section id="the-bernoulli-model" class="slide level2">
<h2>The Bernoulli Model</h2>
<p>For the derivation, let us set <span class="math inline">\(\beta_0 = 0\)</span> such that</p>
<p><span class="math display">\[
p(\mathbf x_i;\boldsymbol\beta)=\frac{e^{\mathbf x_i^\top\boldsymbol\beta}}{1+e^{\mathbf x_i^\top\boldsymbol\beta}},
\qquad 1-p(\mathbf x_i;\boldsymbol\beta)=\frac{1}{1+e^{\mathbf x_i^\top\boldsymbol\beta}}.
\]</span></p>
<p>The data consists of <span class="math inline">\((\boldsymbol{x_1}, y_1), ..., (\boldsymbol{x}_n, y_n)\)</span>, with</p>
<p><span class="math display">\[
y_i \sim \text{Bernoulli}(p(\boldsymbol{x}_i; \boldsymbol{\beta})), \quad 1 \leq i \leq n.
\]</span></p>
</section>
<section id="likelihood-under-logistic-regression" class="slide level2">
<h2>Likelihood Under Logistic Regression</h2>
<p>The likelihood of each data point <span class="math inline">\((\boldsymbol{x}_i, y_i)\)</span> at any <span class="math inline">\(\boldsymbol{\beta}\)</span> is</p>
<p><span class="math display">\[
L(\boldsymbol\beta; \boldsymbol{x}_i, y_i) \propto [p(\mathbf x_i;\boldsymbol\beta)]^{y_i}(1-p(\mathbf x_i;\boldsymbol\beta))^{1-y_i}.
\]</span></p>
<p>with</p>
<p><span class="math display">\[
p(\mathbf x_i;\boldsymbol\beta)=\frac{e^{\mathbf x_i^\top\boldsymbol\beta}}{1+e^{\mathbf x_i^\top\boldsymbol\beta}}
\]</span> The <span class="math inline">\(\propto\)</span> sign means “proportional to”, up to some multiplicative term that does not involve the parameter <span class="math inline">\(\boldsymbol{\beta}\)</span>.</p>
<div class="fragment">
<p>The joint likelihood of all data points is</p>
<p><span class="math display">\[
L(\boldsymbol\beta)=\prod_{i=1}^n [p(\mathbf x_i;\boldsymbol\beta)]^{y_i}(1-p(\mathbf x_i;\boldsymbol\beta))^{1-y_i}
\]</span></p>
</div>
</section>
<section id="log-likelihood-under-logistic-regression" class="slide level2">
<h2>Log-Likelihood Under Logistic Regression</h2>
<p>Taking logs gives</p>
<p><span class="math display">\[
\begin{aligned}
\ell(\boldsymbol\beta)
&amp;=\sum_{i=1}^n\left[y_i\log(p(\mathbf x_i;\boldsymbol\beta))+(1-y_i)\log(1-p(\mathbf x_i;\boldsymbol\beta))\right]\\[0.4em]
&amp;=\sum_{i=1}^n\left[y_i\log\left(\frac{p(\mathbf x_i;\boldsymbol\beta)}{1-p(\mathbf x_i;\boldsymbol\beta)}\right)+\log(1-p(\mathbf x_i;\boldsymbol\beta))\right]\\[0.4em]
&amp;=\sum_{i=1}^n\left[y_i\mathbf x_i^\top\boldsymbol\beta-\log\left(1+e^{\mathbf x_i^\top\boldsymbol\beta}\right)\right].
\end{aligned}
\]</span></p>
</section>
<section id="maximizing-the-log-likelihood" class="slide level2">
<h2>Maximizing the Log-Likelihood</h2>
<p>How do we maximize the log likelihood</p>
<p><span class="math display">\[
\ell(\boldsymbol\beta)=\sum_{i=1}^n\left[y_i\mathbf x_i^\top\boldsymbol\beta-\log\left(1+e^{\mathbf x_i^\top\boldsymbol\beta}\right)\right]?
\]</span></p>
<ul>
<li>Equivalently, minimize <span class="math inline">\(-\ell(\boldsymbol\beta)\)</span> over <span class="math inline">\(\boldsymbol{\beta}\)</span>.</li>
<li>Setting the derivatives equal to zero generally gives no closed-form solution.</li>
<li>We use an <span style="color: maroon;">iterative optimization algorithm</span>.</li>
</ul>
</section>
<section id="gradient-descent" class="slide level2">
<h2>Gradient Descent</h2>
<p>Recall we would like to solve</p>
<p><span class="math display">\[
\min_{\boldsymbol{\beta}\in\mathbb{R}^p}
-\ell(\boldsymbol{\beta})
\]</span></p>
<p>where</p>
<p><span class="math display">\[
-\ell(\boldsymbol{\beta})
=
\sum_{i=1}^{n}
\left[
-y_i\mathbf{x}_i^\top\boldsymbol{\beta}
+
\log\left(1+e^{\mathbf{x}_i^\top\boldsymbol{\beta}}\right)
\right].
\]</span></p>
<div class="fragment">
<p>The gradient at any <span class="math inline">\(\boldsymbol{\beta}\)</span> is that, for any <span class="math inline">\(j\in\{1,\ldots,p\}\)</span>,</p>
<p><span class="math display">\[
-\frac{\partial\ell(\boldsymbol{\beta})}{\partial\beta_j}
=
\sum_{i=1}^{n}
\left[
-y_i
+
\frac{e^{\mathbf{x}_i^\top\boldsymbol{\beta}}}
{1+e^{\mathbf{x}_i^\top\boldsymbol{\beta}}}
\right]x_{ij}
\qquad \text{(verify this!)}
\]</span></p>
</div>
</section>
<section id="gradient-descent-updates-and-stopping" class="slide level2">
<h2>Gradient Descent: Updates and Stopping</h2>
<p>Therefore, at the <span class="math inline">\((k+1)\)</span>th iteration, with the learning rate <span class="math inline">\(\alpha\)</span>,</p>
<p><span class="math display">\[
\widehat{\boldsymbol{\beta}}^{(k+1)}
=
\widehat{\boldsymbol{\beta}}^{(k)}
-
\alpha\sum_{i=1}^{n}
\left[
-y_i
+
\frac{
e^{\mathbf{x}_i^\top\widehat{\boldsymbol{\beta}}^{(k)}}
}{
1+e^{\mathbf{x}_i^\top\widehat{\boldsymbol{\beta}}^{(k)}}
}
\right]\mathbf{x}_i.
\]</span></p>
<p>Initialization <span class="math inline">\(\boldsymbol{\beta}^{(0)}=\mathbf{0}\)</span>.</p>
<p><br></p>
<div class="fragment">
<ul>
<li><p>The objective value stops changing: <span class="math inline">\(\left|\ell(\widehat{\boldsymbol{\beta}}^{(k+1)})-\ell(\widehat{\boldsymbol{\beta}}^{(k)})\right|\)</span> is small, say, <span class="math inline">\(\leq 10^{-6}\)</span>.</p></li>
<li><p>The parameter stops changing: <span class="math inline">\(\left\|\widehat{\boldsymbol{\beta}}^{(k+1)}-\widehat{\boldsymbol{\beta}}^{(k)}\right\|_2\)</span> is small or <span class="math inline">\(\left\|\widehat{\boldsymbol{\beta}}^{(k+1)}-\widehat{\boldsymbol{\beta}}^{(k)}\right\|_2/\left\|\widehat{\boldsymbol{\beta}}^{(k)}\right\|_2\)</span> is small.</p></li>
<li><p>Stop after <span class="math inline">\(M\)</span> iterations for some specified <span class="math inline">\(M\)</span>, e.g.&nbsp;<span class="math inline">\(M=1000\)</span>.</p></li>
</ul>
</div>
</section>
<section id="gradient-descent-1" class="slide level2">
<h2>Gradient Descent</h2>
<p>The negative log-likelihood</p>
<p><span class="math display">\[
J(\boldsymbol\beta)=\sum_{i=1}^n\left[-y_i\mathbf x_i^\top\boldsymbol\beta+\log\left(1+e^{\mathbf x_i^\top\boldsymbol\beta}\right)\right]
\]</span></p>
<p>is <span style="color: maroon;">convex</span> in <span class="math inline">\(\boldsymbol\beta\)</span> (check this!).</p>
<ul>
<li>With an appropriate learning rate, gradient descent can find a global minimum when a finite minimizer exists.</li>
</ul>
</section>
<section id="why-maximum-likelihood" class="slide level2">
<h2>Why Maximum Likelihood?</h2>
<p>The MLE, whenever it can be computed, has many nice properties!</p>
<ul>
<li><span style="color: maroon;">Asymptotically consistent</span>:</li>
</ul>
<p><span class="math display">\[
\widehat{\boldsymbol\beta}\xrightarrow{P}\boldsymbol\beta\quad\text{as }n\to\infty.
\]</span></p>
<ul>
<li><span style="color: maroon;">Asymptotically normal</span>:</li>
</ul>
<p><span class="math display">\[
\sqrt n(\widehat{\boldsymbol\beta}-\boldsymbol\beta)\xrightarrow{d}N(\mathbf 0,\boldsymbol\Sigma).
\]</span></p>
<ul>
<li><span style="color: maroon;">Asymptotically efficient</span>: <span class="math inline">\(\Sigma\)</span> is the “smallest” among all asymptotic unbiased estimators</li>
</ul>
<p>Limitations include computation, model misspecification, etc.</p>
</section>
<section id="inference-under-logistic-regression" class="slide level2">
<h2>Inference Under Logistic Regression</h2>
<p>Let <span class="math inline">\(\widehat{\boldsymbol{\beta}}\)</span> be the MLE of <span class="math inline">\(\boldsymbol{\beta}\)</span>.</p>
<ul>
<li><p>The Z-statistic is similar to the t-statistic in regression, and is defined as</p>
<p><span class="math display">\[
\frac{\widehat{\beta}_j}
{\operatorname{SE}(\widehat{\beta}_j)},
\qquad \forall j\in\{0,1,\ldots,p\},
\]</span></p>
<p>where <span class="math inline">\(\operatorname{SE}(\widehat{\beta}_j)\)</span> is the estimated asymptotic standard error of <span class="math inline">\(\widehat{\beta}_j\)</span>, equal to <span class="math inline">\(\sqrt{\widehat{\Sigma}_{jj}/n}\)</span> using the notation in the previous slide.</p></li>
</ul>
<div class="fragment">
<ul>
<li><p>It produces a p-value for testing the null hypothesis</p>
<p><span class="math display">\[
H_0:\beta_j=0
\qquad \text{vs.} \qquad
H_1:\beta_j\neq0.
\]</span></p>
<p>A large absolute value of the z-statistic or a small p-value indicates evidence against <span class="math inline">\(H_0\)</span>.</p></li>
</ul>
</div>
</section>
<section id="example-default-data" class="slide level2">
<h2>Example: Default Data</h2>
<p>We want to predict a customer’s <span style="color: maroon;">probability of default</span> using student status.</p>
<p>Define</p>
<p><span class="math display">\[
x_i=\begin{cases}1,&amp;\text{customer }i\text{ is a student},\\0,&amp;\text{otherwise},\end{cases}
\qquad
y_i=\begin{cases}1,&amp;\text{customer }i\text{ defaults},\\0,&amp;\text{otherwise}.\end{cases}
\]</span></p>
<p>Fit the logistic model</p>
<p><span class="math display">\[
Y_i\mid x_i\sim\operatorname{Bernoulli}(p_i),\qquad
p_i=\frac{e^{\beta_0+\beta_1x_i}}{1+e^{\beta_0+\beta_1x_i}}.
\]</span></p>
</section>
<section id="example-default-data-1" class="slide level2">
<h2>Example: Default Data</h2>
<p><span class="math display">\[
\log\left(\frac{p_i}{1-p_i}\right)=\beta_0+\beta_1x_{i1}.
\]</span></p>
<p>The fitted maximum likelihood estimates of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> satisfy:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">Std. error</th>
<th style="text-align: right;">Z-statistic</th>
<th style="text-align: right;">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">-3.5</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">-49.55</td>
<td style="text-align: right;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Student (Yes)</td>
<td style="text-align: right;">0.405</td>
<td style="text-align: right;">0.115</td>
<td style="text-align: right;">3.52</td>
<td style="text-align: right;">0.0004</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Using the rounded coefficients:</p>
<p><span class="math display">\[
\widehat p(x=1)=\hat{\mathbb{P}}(\text{default}\mid\text{student})=\frac{e^{-3.5+0.405}}{1+e^{-3.5+0.405}}\approx0.043,
\]</span></p>
<p><span class="math display">\[
\widehat p(x=0)=\hat{\mathbb{P}}(\text{default}\mid\text{non-student})=\frac{e^{-3.5}}{1+e^{-3.5}}\approx0.029.
\]</span></p>
</div>
</section>
<section id="example-default-data-2" class="slide level2">
<h2>Example: Default Data</h2>
<p>Now include balance (<span class="math inline">\(X_1\)</span>), income in thousands of dollars (<span class="math inline">\(X_2\)</span>), and student status (<span class="math inline">\(X_3\)</span>):</p>
<p><span class="math display">\[
\log\left(\frac{p_i}{1-p_i}\right)=\beta_0+\beta_1x_{i1}+\beta_2x_{i2}+\beta_3x_{i3}.
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">Std. error</th>
<th style="text-align: right;">Z-statistic</th>
<th style="text-align: right;">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">-10.87</td>
<td style="text-align: right;">0.492</td>
<td style="text-align: right;">-22.08</td>
<td style="text-align: right;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Balance</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.0002</td>
<td style="text-align: right;">24.74</td>
<td style="text-align: right;">&lt;0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Income (thousands)</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.0082</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.712</td>
</tr>
<tr class="even">
<td style="text-align: left;">Student (Yes)</td>
<td style="text-align: right;">-0.647</td>
<td style="text-align: right;">0.2362</td>
<td style="text-align: right;">-2.74</td>
<td style="text-align: right;">0.0062</td>
</tr>
</tbody>
</table>
<p><strong>Question:</strong> How does the student coefficient change?</p>
</section>
<section id="evaluating-classifiers" class="slide level2">
<h2>Evaluating Classifiers</h2>
<p>Several metrics can evaluate a classifier.</p>
<p>The most common is <span style="color: maroon;">classification accuracy</span>:</p>
<p><span class="math display">\[
\operatorname{Accuracy}=\frac{\text{number of correct predictions}}{\text{number of observations}}.
\]</span></p>
<p><br></p>
<p>For binary classification, there are a few more we can use.</p>
</section>
<section id="continued-example-default-data" class="slide level2">
<h2>Continued Example: Default Data</h2>
<p>Classify default using credit card balance and student status.</p>
<p>The <span style="color: maroon;">confusion matrix</span> of fitted logistic regression:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Predicted default</th>
<th style="text-align: right;">Actual No</th>
<th style="text-align: right;">Actual Yes</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">9,644</td>
<td style="text-align: right;">252</td>
<td style="text-align: right;">9,896</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">104</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">9,667</td>
<td style="text-align: right;">333</td>
<td style="text-align: right;">10,000</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>The <span style="color: maroon;">training error rate</span> is</p>
<p><span class="math display">\[
\frac{23+252}{10000}=2.75\%.
\]</span></p>
</section>
<section id="types-of-classification-errors" class="slide level2">
<h2>Types of Classification Errors</h2>
<p>The positive class is <strong>default</strong>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Predicted default</th>
<th style="text-align: right;">Actual No</th>
<th style="text-align: right;">Actual Yes</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">9,644</td>
<td style="text-align: right;">252</td>
<td style="text-align: right;">9,896</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">104</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">9,667</td>
<td style="text-align: right;">333</td>
<td style="text-align: right;">10,000</td>
</tr>
</tbody>
</table>
<ul>
<li><span style="color: maroon;">False positive rate (FPR)</span>: the fraction of actual negatives classified as positive.</li>
</ul>
<p><span class="math display">\[
\operatorname{FPR}=\frac{\operatorname{FP}}{\operatorname{TN}+\operatorname{FP}}=\frac{23}{9667}\approx0.24\%.
\]</span></p>
<ul>
<li><span style="color: maroon;">False negative rate (FNR)</span>: the fraction of actual positives classified as negative.</li>
</ul>
<p><span class="math display">\[
\operatorname{FNR}=\frac{\operatorname{FN}}{\operatorname{TP}+\operatorname{FN}}=\frac{252}{333}\approx75.7\%.
\]</span></p>
<p>A credit card company trying to identify high-risk customers misses most customers who default.</p>
</section>
<section id="controlling-the-false-negative-rate" class="slide level2">
<h2>Controlling the False Negative Rate</h2>
<p><strong>Question:</strong> How could we modify the classifier to lower its false negative rate?</p>
<p><br></p>
<div class="fragment">
<p>The current rule uses a <span style="color: maroon;">threshold</span> of <span class="math inline">\(0.5\)</span>:</p>
<p><span class="math display">\[
\widehat y_i=\begin{cases}
1\;\text{(default)},&amp;\widehat p(x_i)\geq0.5,\\
0\;\text{(non-default)},&amp;\widehat p(x_i)&lt;0.5.
\end{cases}
\]</span></p>
<p>We want fewer actual defaults to receive a non-default prediction.</p>
</div>
</section>
<section id="changing-the-threshold" class="slide level2">
<h2>Changing the Threshold</h2>
<p>To lower FNR, classify an observation as positive when</p>
<p><span class="math display">\[
\widehat p(x)\geq t
\]</span></p>
<p>for a <span style="color: maroon;">lower threshold</span> <span class="math inline">\(0\leq t&lt;0.5\)</span>.</p>
<ul>
<li>Why is <span class="math inline">\(t=0.5\)</span> a natural starting point?</li>
<li>What happens when <span class="math inline">\(t=0\)</span>?</li>
<li>What happens when <span class="math inline">\(t=1\)</span>?</li>
</ul>
</section>
<section id="trade-off-between-fpr-and-fnr" class="slide level2">
<h2>Trade-Off Between FPR and FNR</h2>
<p>Varying the threshold changes the balance between <span style="color: maroon;">false positives</span> and <span style="color: maroon;">false negatives</span>.</p>

<img data-src="images/Week5-Tradeoff.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"></section>
<section id="roc-curve" class="slide level2">
<h2>ROC Curve</h2>
<p>The <span style="color: maroon;">ROC curve</span> plots FPR against TPR <span class="math inline">\(=1-\operatorname{FNR}\)</span> across thresholds.</p>

<img data-src="images/Week5-AUROC.png" class="quarto-figure quarto-figure-center r-stretch" style="width:50.0%"><p>The overall performance of a classifier, summarized over all threshholds, is given by the <span style="color: maroon;">area under the curve (AUC)</span>. High AUC is good.</p>
</section>
<section id="more-binary-classification-metrics" class="slide level2">
<h2>More Binary Classification Metrics</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Actual class</th>
<th style="text-align: right;">Predicted negative</th>
<th style="text-align: right;">Predicted positive</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Negative</td>
<td style="text-align: right;">TN</td>
<td style="text-align: right;">FP</td>
<td style="text-align: right;"><span class="math inline">\(N\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Positive</td>
<td style="text-align: right;">FN</td>
<td style="text-align: right;">TP</td>
<td style="text-align: right;"><span class="math inline">\(P\)</span></td>
</tr>
</tbody>
</table>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Definition</th>
<th style="text-align: left;">Other name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">False positive rate</td>
<td style="text-align: left;"><span class="math inline">\(\operatorname{FP}/N\)</span></td>
<td style="text-align: left;"><span class="math inline">\(1-\text{specificity}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">True positive rate</td>
<td style="text-align: left;"><span class="math inline">\(\operatorname{TP}/P\)</span></td>
<td style="text-align: left;">Sensitivity, recall</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Specificity</td>
<td style="text-align: left;"><span class="math inline">\(\operatorname{TN}/N\)</span></td>
<td style="text-align: left;">True negative rate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Positive predictive value</td>
<td style="text-align: left;"><span class="math inline">\(\operatorname{TP}/(\operatorname{TP}+\operatorname{FP})\)</span></td>
<td style="text-align: left;">Precision</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Negative predictive value</td>
<td style="text-align: left;"><span class="math inline">\(\operatorname{TN}/(\operatorname{TN}+\operatorname{FN})\)</span></td>
<td style="text-align: left;">NPV</td>
</tr>
</tbody>
</table>
<p>The denominators distinguish metrics that condition on the <strong>actual class</strong> from those that condition on the <strong>predicted class</strong>.</p>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<ul>
<li><p>The Bayes classifier assigns each observation to the most probable class. Its expected error rate is the smallest possible, but the true conditional probabilities are usually unknown.</p></li>
<li><p>kNN estimates class probabilities using nearby training observations. Choosing <span class="math inline">\(k\)</span> balances flexibility and stability; scaling and dimensionality also affect performance.</p></li>
<li><p>Logistic regression models the log-odds as a linear function of predictors. We estimate its coefficients by maximum likelihood using iterative optimization, then convert fitted probabilities into class labels.</p></li>
<li><p>Classifier evaluation requires more than overall accuracy. Confusion-matrix metrics reveal different errors, changing the threshold trades false positives against false negatives, and ROC curves summarize this trade-off across thresholds.</p></li>
</ul>
<p><strong>Announcements:</strong></p>
<ul>
<li>Assignment due October 7th</li>
<li>No class, tutorial or office hour on Monday, October 12 (Thanksgiving)</li>
</ul>
<p><strong>Next Class:</strong> Multiclass logistic regression + Linear discriminant analysis</p>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<div style="font-size: 15px; display: flex; justify-content: space-between; width: 92%; margin-left: 4em;">
<span style="flex: 1; text-align: left;">STA314: Statistical Methods for Machine Learning I</span><span style="flex: 1; text-align: center;">Bayes Classifier, kNN and Logistic Regression</span><span style="flex: 1;"></span>
</div>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"right","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true,"width":"wide"},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script type="ojs-module-contents">
    eyJjb250ZW50cyI6W119
    </script>
    <script type="module">
    if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
    window._ojs.paths.runtimeToDoc = "../..";
    window._ojs.paths.runtimeToRoot = "../..";
    window._ojs.paths.docToRoot = "";
    window._ojs.selfContained = false;
    window._ojs.runtime.interpretFromScriptTags();
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>